os: linux
dist: xenial
sudo: false

language: go
go: 1.14.x
go_import_path: github.com/syberalexis/linky-exporter

env:
  global:
    - BUILD_GO111MODULE=on
  matrix:
    - BUILD_GOOS=linux BUILD_GOARCH=amd64
    - BUILD_GOOS=linux BUILD_GOARCH=arm BUILD_GOARM=5
    - BUILD_GOOS=linux BUILD_GOARCH=arm BUILD_GOARM=6
    - BUILD_GOOS=linux BUILD_GOARCH=arm BUILD_GOARM=7
    - BUILD_GOOS=linux BUILD_GOARCH=arm64
    - BUILD_GOOS=windows BUILD_GOARCH=amd64
    - BUILD_GOOS=windows BUILD_GOARCH=arm BUILD_GOARM=5
    - BUILD_GOOS=windows BUILD_GOARCH=arm BUILD_GOARM=6
    - BUILD_GOOS=windows BUILD_GOARCH=arm BUILD_GOARM=7
script:
  - GOOS=${BUILD_GOOS} GOARCH=${BUILD_GOARCH} GOARM=${BUILD_GOARM} make clean build

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true